import { SENTIMENT_LABELS } from "./constants.js";

export function formatSummaryForClipboard(result) {
  if (!result) {
    return "";
  }

  const lines = [
    `QuickDigest AI — ${result.title || "Summary"}`,
    result.url ? `URL: ${result.url}` : "",
    "",
    `TL;DR: ${result.tldr || result.summary}`,
    "",
    "Summary:",
    result.summary || "",
    "",
    "Bullet Summary:",
    ...(result.bullets || []).map((item) => `• ${item}`),
    "",
    "Key Takeaways:",
    ...(result.takeaways || []).map((item, i) => `${i + 1}. ${item}`),
    "",
    "Action Items:",
    ...(result.actionItems || []).map((item, i) => `${i + 1}. ${item}`),
    "",
    `Reading time: ~${result.readingTimeMinutes} min`,
    `Sentiment: ${SENTIMENT_LABELS[result.sentiment] || result.sentiment}`,
    `Language: ${(result.language || "en").toUpperCase()}`,
    `Engine: ${result.engine || "local"}`,
  ];

  return lines.filter((line, index) => line !== "" || index < 4).join("\n");
}

export function formatSummaryForDownload(result) {
  return `${formatSummaryForClipboard(result)}\n\nGenerated by QuickDigest AI (on-device, privacy-first).\n`;
}
